spring:
  application:
    name: user-service
  profiles:
    active: dev
  sleuth:
      web:
        client:
          enabled: true
        sampler:
          probability: 1.0    # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/    # 指定了 Zipkin 服务器的地址

server:
  port: 5200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/

feign:
  hystrix:
    enabled: true
logging:
  level:
    com:
      lockie:
        user:
          mapper: debug