spring:
  application:
    name: address-service
  profiles:
    active: dev

server:
  port: 5400


eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/


feign:
  hystrix:
    enabled: true
logging:
  level:
    com:
      lockie:
        address:
          mapper: debug

